packages:
  - 'directus/**'
  - nuxt
catalog:
  '@antfu/eslint-config': ^5.4.1
  '@directus/extensions-sdk': ^16.0.2
  '@directus/shared': ^9.24.0
  '@directus/types': ^13.2.3
  '@neondatabase/api-client': ^2.2.0
  '@types/node': ^24.5.2
  '@types/qrcode-terminal': ^0.12.2
  '@vue/tsconfig': ^0.8.1
  eslint: ^9.36.0
  open: ^10.2.0
  qrcode-terminal: ^0.12.0
  ts-pattern: ^5.8.0
  tsx: ^4.20.6
  type-fest: ^5.0.1
  typescript: ^5.9.2
  vitest: ^3.2.4
  vue: ^3.5.22
  zca-js: ^2.0.1
